version: '3.8'

services:
  maven_build:
    image: maven:3.8.4-openjdk-17
    volumes:
      - ./src/main:/app
    working_dir: /app
    command: mvn clean package

  app:
    build: 
      context: .
      dockerfile: Dockerfile
    ports:
      - "80:80"
    depends_on:
      - maven_build
