name: Maven CI Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '11'

      - name: Build with Maven
        run: mvn -B package --file pom.xml

  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '11'

      - name: Run Maven Tests
        run: mvn test

  dependency-check:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        distribution: 'adopt'
        java-version: '11'

    - name: Set JAVA_HOME for Dependency Check
      run: echo "JAVA_HOME=${RUNNER_TOOL_CACHE}/Java_Adopt_jdk/11.0.23-9/x64" >> $GITHUB_ENV

    - name: Run OWASP Dependency Check
      run: |
        docker run --name owaspdependencychecklatest_cfa219 \
          --label bd5312 \
          --workdir /github/workspace \
          --rm \
          -e "JAVA_HOME=${RUNNER_TOOL_CACHE}/Java_Adopt_jdk/11.0.23-9/x64" \
          -v "/var/run/docker.sock":"/var/run/docker.sock" \
          -v "/home/runner/work/_temp/_github_home":"/github/home" \
          -v "/home/runner/work/_temp/_github_workflow":"/github/workflow" \
          -v "/home/runner/work/_temp/_runner_file_commands":"/github/file_commands" \
          -v "/home/runner/work/MAven/MAven":"/github/workspace" \
          owasp/dependency-check:latest \
          --scan /github/workspace --format ALL --project CI

