name: Java CI with Maven and Dependency Check

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up JDK
      uses: actions/setup-java@v2
      with:
        java-version: '17' # or the version you need

    - name: Build with Maven
      run: mvn -B package --file pom.xml

    - name: Run tests
      run: mvn test --file pom.xml

    - name: Dependency Check
      uses: docker://owasp/dependency-check:latest
      with:
        args: --scan /github/workspace --format ALL --project CI

    - name: Archive report
      uses: actions/upload-artifact@v2
      with:
        name: dependency-check-report
        path: dependency-check-report

    - name: Generate HTML report
      run: docker run --rm -v "$(pwd)/dependency-check-report:/report" owasp/dependency-check --project CI --scan /report --format HTML --output /report/dependency-check-report.html

    - name: Print HTML report path
      run: echo "Dependency Check HTML report: file://$(pwd)/dependency-check-report/dependency-check-report.html"
